In [30]:
import pandas as pd
import numpy as np
from numpy.linalg import inv

In [2]:
base=pd.read_csv('data.csv')

In [3]:
base;

In [4]:
base.shape

(11914, 16)

In [5]:
base['Make'].value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

In [6]:
base[base['Make']=='Audi']['Model'].nunique()

34

In [7]:
base.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [8]:
base['Engine Cylinders'].mode()

0    4.0
Name: Engine Cylinders, dtype: float64

In [9]:
median=base['Engine Cylinders'].median()
median

6.0

In [10]:
base['Engine Cylinders'].fillna(median,inplace=True)

In [11]:
base['Engine Cylinders'].isnull().sum()

0

In [12]:
base['Engine Cylinders'].median()

6.0

In [17]:
table=base[base['Make']=='Lotus'][['Engine HP','Engine Cylinders']].drop_duplicates()

In [41]:
table

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [43]:
X=np.array(table)
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [49]:
XTX=np.matmul(X.T,X)

In [54]:
xinv=inv(XTX)

In [52]:
y=np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [53]:
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [56]:
a=np.matmul(xinv,X.T)

In [57]:
np.matmul(a,y)

array([  4.59494481, -63.56432501])